Failure: ImportError (No module named pandas) ... ERROR

======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/afs/crc.nd.edu/user/c/crondonm/Private/TrackingR-Estimates/code/python/tests/tests_dataset.py", line 7, in <module>
    import pandas as pd
ImportError: No module named pandas

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
